cultuurnet/udb3-php

- src/LabelCollection.php
- src/Offer/Commands/AbstractImportLabels.php
- src/Offer/Offer.php
- src/Offer/OfferCommandHandler.php
- src/Organizer/Commands/ImportLabels.php
- src/Organizer/Organizer.php
- src/Organizer/OrganizerCommandHandler.php
- test/Event/Commands/ImportLabelsTest.php
- test/Offer/OfferCommandHandlerTest.php
- test/Offer/OfferTest.php
- test/Organizer/OrganizerCommandHandlerTest.php
- test/Organizer/OrganizerTest.php
Any labels in this option will be kept if already applied on the offer in the past. If not they will be ignored.
These labels are not checked by the label security checks since either they are already on the offer or they are ignored.
> III-2876: Add option to keep certain labels when importing

- src/Role/ReadModel/Search/Doctrine/SchemaConfigurator.php
These schema classes are no longer being used to set up the actual application tables since https://bitbucket.org/cultuurnet/udb3-vagrant/pull-requests/60, but they're still being used for integration tests at this point.
> III-2917 Setup query constraint column as longtext

- src/Organizer/OrganizerLDProjector.php
- src/Organizer/WorkflowStatus.php
- test/Organizer/OrganizerLDProjectorTest.php
- Added `workflowStatus: active` property to active organizers' json-ld
-------------------------------------------------
⚠️ This will require a `composer up cultuurnet/udb3` in `udb3-silex` after it gets merged.
> III-2921 Add workflowStatus to active organizers

- composer.json
- `guzzlehttp/psr7` is now constrained to `^1.2` instead of `~1.2.3`, allowing us to upgrade to `1.4` in applications that want to upgrade `guzzlehttp/guzzle` to version `6.3` and up.
> Loosen up version constraint on guzzlehttp/psr7

- src/Event/Event.php
- src/Event/IncompatibleAudienceType.php
- src/Event/ValueObjects/LocationId.php
- test/Event/EventTest.php
- When an event uses a dummy place for bookable events (for education), we no longer allow changing the audience type to something other than education.
---
Ticket: https://jira.uitdatabank.be/browse/III-3051
---
Note: This still requires bootstrapping in `udb3-silex` to statically set the list of dummy locations on the `LocationId` value object
> III-3051 - Don't allow updating with incompatible audienceType when using dummy place in event

- src/Event/Event.php
- test/Event/EventTest.php
- When creating an event with a dummy education location, the event's audience type will automatically be set to education.
- When updating an event to link it to a dummy education location, the event's audience type will automatically be set to education.
---
Ticket: https://jira.uitdatabank.be/browse/III-3050
> Automatically set audienceType to education for events with a dummy location

- src/Event/LocationMarkedAsDuplicateProcessManager.php
- test/Event/LocationMarkedAsDuplicateProcessManagerTest.php
- Process manager that updates events who's place was marked as duplicate, to change it to the canonical place.
---
Ticket: https://jira.uitdatabank.be/browse/III-3043
---
This will also need to be bootstrapped in udb3-silex. I've updated https://jira.uitdatabank.be/browse/III-3045 to mention that it will require some bootstrapping when we add the console command.
> III-3043 Update events with a place that was marked as duplicate

- src/Place/Events/MarkedAsCanonical.php
- src/Place/MarkAsDuplicateCommandHandler.php
- src/Place/Place.php
- src/Place/ReadModel/JSONLD/PlaceLDProjector.php
- test/Place/Events/MarkedAsCanonicalTest.php
- test/Place/PlaceTest.php
- Duplicates of a duplicate will now be passed along when marking a place as canonical. This will make sure search will always return events for the proper canonical.
---
Ticket: https://jira.uitdatabank.be/browse/III-3060
> III-3060 - Project duplicates of duplicate in read models for search indexing

- src/Event/RelocateEventToCanonicalPlace.php
- src/Place/CanonicalPlaceRepository.php
- src/Place/Place.php
- test/Event/RelocateEventToCanonicalPlaceTest.php
- test/Place/CanonicalPlaceRepositoryTest.php
- Process manager to update locations to canonical places for events that were created or updated to use a place that was marked as a duplicate before
---
Ticket: https://jira.uitdatabank.be/browse/III-3047
> III-3047 - Always use canonical place when creating or updating an event

- src/Event/Event.php
- The automatic `updateAudience` call failed because `$this->locationId` is `null` after a cdbxml import because we do not have the cdbxml id extractor service here. (Right after this step we do set the `$this->locationId` though because we call `UpdateLocation` from the cdbxml importer.)
---
https://jira.uitdatabank.be/browse/III-3069
> Fix event cdbxml imports

- src/Event/Event.php
- test/Event/EventCommandHandlerTest.php
- `audienceType` is now updatable after changing the location on an event from a dummy location to a regular location (using the deprecated major-info command).
---
Note that this will require `composer up cultuurnet/udb3` to be run in `udb3-silex` to update the dependency there after merging this.
> Fix audienceType not being updatable after removing dummy location

- src/Event/Event.php
- test/Event/EventCommandHandlerTest.php
- Setting an event's location to a dummy location via the deprecated UpdateMajorInfo command now sets the event's audienceType to education.
> Automatically set the audienceType to education if major info update contains a dummy location

- src/Offer/Commands/AbstractImportLabels.php
- src/Offer/Offer.php
- src/Offer/OfferCommandHandler.php
- test/Offer/OfferCommandHandlerTest.php
- test/Offer/OfferTest.php
- Importing labels now requires you specify which labels the import is allowed to remove from the offer. It used to remove all non-excluded labels, but that turned out to be too eager, also removing labels that were added async (e.g. uitpas)
> III-3087 - Explicitly tell ImportLabels which labels it is allowed to remove

- src/Event/LocationMarkedAsDuplicateProcessManager.php
- test/Event/LocationMarkedAsDuplicateProcessManagerTest.php
- The "location marked as duplicate" process manager now looks up the related events by using `location.mainId` instead of `location.id`, so we don't get events that are actually linked to the canonical place instead of the duplicate place
> III-3080 Find related events by using location.mainId instead of location.id

- src/Event/LocationMarkedAsDuplicateProcessManager.php
- src/Search/ResultsGenerator.php
- When marking a location as duplicate of another, we print more info to the CLI output (using a logger) so we can see how many events should be updated according to SAPI3 before we actually loop over them.
---
Ticket: https://jira.uitdatabank.be/browse/III-3080
> III-3080 Add more logging to SAPI3 results generator

- src/Event/LocationMarkedAsDuplicateProcessManager.php
- Fixed the pagination of events that should be updated. Updating them influenced the search results and caused results to be shifted to other pages, so they got skipped.
---
Ticket: https://jira.uitdatabank.be/browse/III-3080
> III-3080 Fix pagination of events that should be relocated

- src/Offer/AbstractGeoCoordinatesCommandHandler.php
- test/Event/GeoCoordinatesCommandHandlerTest.php
Changed
- updated AbstractGeoCoordinatesto skip geo coordinates update if geocordinates can not be resolved
> feature/III-3091: Skip GeoCordinates update if the geocordinates can not be resolved

- composer.json
- In Composer 2.0 uppercase characters will be disallowed in package names. Composer currently returns a deprecation warning for this (not an error), but Packagist trips over this and refuses to update the udb3 package now.
---
Original email:
```
The cultuurnet/udb3 package of which you are a maintainer has
failed to update due to invalid data contained in your composer.json.
Please address this as soon as possible since the package stopped updating.
It is recommended that you use `composer validate` to check for errors when you
change your composer.json.
Below is the full update log which should highlight errors as
"Skipped branch ...":
[Composer\Repository\InvalidRepositoryException]: Some branches contained invalid data and were discarded, it is advised to review the log and fix any …
```
> Fix deprecation warning that prevents packagist from updating

- src/BackwardsCompatiblePayloadSerializerFactory.php
- Fixed "LocationId can't have an empty value" errors caused by corrupt data in the production event store
---
Ticket: https://jira.uitdatabank.be/browse/III-3055
---
⚠️ After merging this, we still need to run `composer up cultuurnet/udb3` in `udb3-silex` and commit the `composer.lock` change before we can deploy this.
> III-3055 Fix LocationId can't have empty value error

- src/Offer/OfferCommandHandler.php
- test/Event/EventCommandHandlerTest.php
- test/Offer/OfferCommandHandlerTest.php
- Some queue consumers dispatch Add/Remove label commands for labels that might not exist, and they are not automatically created by the EventEditingService in these cases.
> Fix queue consumers crashing on Add/RemoveLabel commands

- src/Calendar.php
- src/CalendarFactory.php
- test/CalendarFactoryTest.php
- Projection of events with multiple dates incorrectly used the end date of the last added date instead of the chronological last date of the added timestamps.
- Projection of events with multiple dates incorrectly used the start date of the first added date instead of the chronological first date of the added timestamps.
---
Issue: https://jira.uitdatabank.be/browse/III-3132
---
After this is merged we should update this dependency in https://github.com/cultuurnet/udb3-silex
> Fix end dates in JsonLD projection of events with multiple dates 

- src/Calendar.php
- test/CalendarTest.php
- Timestamps of events with multiple timestamps are now always sorted chronologically
---
Issue: https://jira.uitdatabank.be/browse/III-3132
---
Note that we have to update the dependency in `udb3-silex` before this will work
> III-3132: Sort timestamps of events

- src/Offer/AgeRange.php
- test/Offer/AgeRangeTest.php
- Fixed existing age ranges without from in JSON-LD read models. The age range in the event store is converted to this value object, so if we set from to 0 if it's null here, all missing froms in the event store will be fixed on the fly.
---
Ticket: https://jira.uitdatabank.be/browse/III-3399
Note: This will require a `composer up cultuurnet/udb3-php` in `udb3-silex` after merging it.
Related PR: https://github.com/cultuurnet/udb3-models/pull/9
> Fix existing age ranges without from

- src/Calendar.php
- test/Calendar/CalendarConverterTest.php
- test/CalendarTest.php
- test/Event/Events/CalendarUpdatedTest.php
- test/Event/Events/EventCopiedTest.php
- test/Place/Events/CalendarUpdatedTest.php
- Removed requirement for start and end date for single and multiple calendars, as it can be determined based on the timestamps. This adds a hard requirement to pass timestamps though, which has a consequence for existing calendars in the event store which is why there's some backwards-compatibility workarounds.
---
Ticket: https://jira.uitdatabank.be/browse/III-3433
Related PR: https://github.com/cultuurnet/udb3-silex/pull/490
Note: This will require a `composer up cultuurnet/udb3` in https://github.com/cultuurnet/udb3-silex/pull/490 after this PR is merged
> III-3433 Make start and end date optional for single and multiple calendars

- .github/workflows/ci.yml
- Pin the Github Action to use Composer v1
- Remove the caching because this project has no `composer.lock` file
> Pin to composer v1 in Github Actions

- src/Calendar.php
- test/CalendarTest.php
- Fixed issue with `Calendar::deserialize()` causing the status in subEvents to be overwritten by a previously derived top status
- When a `Calendar` object has a top status that is incorrect compared to the statuses in its subEvents, it will get corrected when projecting it to JSON-LD. That way we still have the originally submitted data in case there's a bug in the conversion, or if the logic should ever change. (Cases where this can happen is when updating the full Calendar through `UpdateCalendar` or `UpdateMajorInfo`)
---
Ticket: https://jira.uitdatabank.be/browse/III-3679
I've added additional info in the commit descriptions, so if you go through them one by one you can find extra context there.
> III-3679 Fix an incorrect top status in the Calendar when projecting to JSON-LD

- src/Calendar.php
- test/CalendarTest.php
- Take into account udb3-models Calendar top-level status when creating a udb3-php Calendar. But make sure to only modify the top-level status and leave the sub-events untouched.
---
Ticket: https://jira.uitdatabank.be/browse/III-3660
> Add udb3-models top level status on udb3-php calendar
