src/Moderation/Sapi3/NeedsModerationNarrower.php
test/Moderation/Sapi3/NeedsModerationNarrowerTest.php

- Offers that aren't available for everyone are no longer returned for moderation
---
https://jira.uitdatabank.be/browse/III-2922

Only allow moderation for offers that are available to everyone

---

src/Offer/ReadModel/JSONLD/CdbXMLItemBaseImporter.php
test/Event/ReadModel/JSONLD/CdbXMLImporterTest.php
test/Event/ReadModel/JSONLD/event_with_invalid_base_price.cdbxml.xml
test/Event/ReadModel/JSONLD/event_with_zero_base_price.cdbxml.xml

- Bug where events with price value 0 didn't receive the correct priceInfo property after importing the xml from udb2
---
https://jira.uitdatabank.be/browse/III-2661

Missing priceInfo property on events imported through xml with price value 0

---

src/Place/Place.php

- Added some real type hints to replace certain doc blocks
- Actualized a todo so it can be tackled in the near future

Clean up Place aggregate root a bit

---

src/Place/ReadModel/JSONLD/PlaceLDProjector.php
test/Place/ReadModel/JSONLD/PlaceLDProjectorTest.php

- `duplicatedBy` property on JSON-LD of canonical places
- `duplicateOf` property on JSON-LD of duplicate places
---
Ticket: https://jira.uitdatabank.be/browse/III-3044

Project duplicatedBy and duplicateOf properties

---

src/Event/LocationMarkedAsDuplicateProcessManager.php
test/Event/LocationMarkedAsDuplicateProcessManagerTest.php

- The `LocationMarkedAsDuplicateProcessManager` now uses SAPI3 to find related events, so it also contains deleted events.
---
Ticket: https://jira.uitdatabank.be/browse/III-3070

III-3070 Use search service to find related events of duplicate place

---

src/Event/ReadModel/History/HistoryProjector.php
src/Event/ReadModel/History/Log.php
src/Offer/ReadModel/History/OfferHistoryProjector.php
test/Event/ReadModel/History/HistoryProjectorTest.php

- API key added to Log
- projectors updated to use API key from Metadata
[Jira](https://jira.uitdatabank.be/browse/III-3113)

Feature: III-3113

---

src/Event/ReadModel/History/HistoryProjector.php
src/Event/ReadModel/History/Log.php
src/Offer/ReadModel/History/OfferHistoryProjector.php
test/Event/ReadModel/History/HistoryProjectorTest.php

##Added
-API field to Log
##Changed
- projectors updated to get API filed from metadata
[Jira](https://jira.uitdatabank.be/browse/III-3114)

Feature: III-3114

---

src/Event/ReadModel/JSONLD/EventLDProjector.php
test/Event/ReadModel/JSONLD/EventLDProjectorTest.php
test/Event/ReadModel/JSONLD/copied_event_without_working_hours.json

- regression test for periodic events copied without working hours
- logic to handle a special case of copying event with week scheme removed
[Jira](https://jira.uitdatabank.be/browse/III-3146)

Feature: III-3146

---

src/Event/EventThemeResolver.php

-  new themes to "Kamp of vakantie"
[Jira](https://jira.uitdatabank.be/browse/III-3154)

Feature: III-3154

---

src/Search/ResultsGenerator.php
src/Search/Sapi3SearchService.php

- Added logging to the SAPI3 search service to log request and response data so we can better debug the export issue
---
Ticket: https://jira.uitdatabank.be/browse/III-3190

Log sapi3 requests and response data

---

composer.json
src/Http/JwtPsr7RequestAuthorizer.php
test/Http/JwtPsr7RequestAuthorizerTest.php
test/Offer/DefaultExternalOfferEditingServiceTest.php

- Removed cultuurnet/symfony-security-jwt dependency

III-3197 Remove cultuurnet/symfony-security-jwt dependency

---

src/Organizer/Events/AddressRemoved.php
src/Organizer/Organizer.php
test/Organizer/OrganizerTest.php

Feature: III-3227

---

src/Organizer/Events/ContentTypes.php

- AddressRemoved content type
[Jira](https://jira.uitdatabank.be/browse/III-3227)

Feature: III-3227 

---

src/Role/ValueObjects/Permission.php
test/Role/ValueObjects/PermissionTest.php

- Permission to create productions: `Producties aanmaken`

Add Permission to create productions

---

.github/workflows/ci.yml
src/Offer/Events/Moderation/AbstractPublished.php

- Fix unknown class constant ATOM
---
Ticket: https://jira.uitdatabank.be/browse/III-3498

Run github actions on multiple php versions

---

phpstan.neon
test/Event/Events/ContactPointUpdatedTest.php
test/EventSourcing/DBAL/AggregateAwareDBALEventStoreTest.php
test/Label/ValueObjects/LabelNameTest.php
test/Media/ImageCollectionTest.php
test/Offer/Events/AbstractContactPointUpdatedTest.php
test/Offer/IriOfferIdentifierFactoryTest.php
test/Offer/OfferIdentifierCollectionTest.php
test/TimestampTest.php

- PHPStan check is now green at level 1

Increase phpstan level to 1

---

src/Calendar.php
src/Event/ValueObjects/Status.php
src/Event/ValueObjects/StatusReason.php
src/Event/ValueObjects/StatusType.php
src/Timestamp.php
test/CalendarTest.php
test/Event/ValueObjects/EventStatusTest.php
test/Event/ValueObjects/StatusTest.php
test/TimestampTest.php

- EventStatus and EventStatusReason are now renamed to just Status and StatusReason
- The values for offer status were changed to `available`, `unavailable` and `temporarily unavailable`

Refactor event status

---

.github/workflows/ci.yml

- Added the php.ini for xdebug 3 and setting `xdebug.mode=coverage`

Fix for switch to xdebug 3 by setting xdebug mode to coverage.

---

.github/workflows/ci.yml
src/Calendar.php
src/Offer/Events/StatusUpdated.php
test/CalendarTest.php
test/Offer/Events/StatusUpdatedTest.php

- Added a new StatusUpdated event inside the offer namespace to be used by the places and events.
---
Ticket: https://jira.uitdatabank.be/browse/III-3656

Add a StatusUpdated event for offers.

---

src/Calendar.php
test/CalendarTest.php
test/Event/Events/CalendarUpdatedTest.php
test/Event/Events/EventCreatedTest.php
test/Event/Events/MajorInfoUpdatedTest.php
test/Place/Events/CalendarUpdatedTest.php
test/Place/Events/PlaceCreatedTest.php

- Serialize and deserialize the status of an offer to the Event Store
---
Ticket: https://jira.uitdatabank.be/browse/III-3671

III-3671 Serialize and deserialize the status of an offer to the Event Store

---

composer.json

- Removed unused composer dependencies

Remove unused composer dependencies
